spring.application.name=book-store

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27020
spring.data.mongodb.database=mydatabase
spring.data.mongodb.username=root
spring.data.mongodb.password=secret
spring.data.mongodb.authentication-database=admin

#spring.security.user.name=root1
#spring.security.user.password=secret1

